[package]
name = "pd2-filter-forge"
version = "0.3.3"
description = "Loot filter editor for Project Diablo 2"
authors = []
edition = "2024"
rust-version = "1.90"

[lib]
name = "pd2_filter_forge_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.0", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.12.0", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2.6.0"
ureq = "2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
